title: eHälsa Sverige
title_short: eHälsa Sve
email: kontakt@example.com
description: "eHälsa Sverige är ett privat initiativ med visionen att vara en samlingsplats för alla som påverkas av eHälsa: patienter, vårdpersonal, beslutsfattare, leverantörer och alla som är nyfikna på att lära sig om eller börja arbeta inom området."
descriptionHTML: "<b>eHälsa Sverige</b> är ett privat initiativ med visionen att vara en samlingsplats för alla som påverkas av eHälsa: patienter, vårdpersonal, beslutsfattare, leverantörer och alla som är nyfikna på att lära sig om eller börja arbeta inom området."
lang: sv
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ehalsasverige.se" # the base hostname & protocol for your site, e.g. http://example.com
social:
  twitter:
    username: "@ehalsasverige"
    profile: "https://twitter.com/ehalsasverige"
  linkedin: "https://www.linkedin.com/company/ehalsasverige/"
  facebook: "https://www.facebook.com/ehalsasverige"
  vimeo: "https://vimeo.com/ehalsasverige"

serviceWorker: false

microserver:
  karta:
    live: "https://ehalsasverige.se/feed/karta.json"
    local: "http://0.0.0.0:9001"
  event:
    live: "https://ehalsasverige.se/feed/event.json"
    local: "http://0.0.0.0:9002"
  nyheter:
    live: "https://ehalsasverige.se/feed/nyheter/all.json"
    local: "http://0.0.0.0:9003"
  nyheter_ehalsomyndigheten:
    live: "https://ehalsasverige.se/feed/nyheter/ehalsomyndigheten.json"
    local: "http://0.0.0.0:9005"
  nyheter_skr:
    live: "https://ehalsasverige.se/feed/nyheter/skr.json"
    local: "http://0.0.0.0:9006"
  nyheter_socialstyrelsen:
    live: "https://ehalsasverige.se/feed/nyheter/socialstyrelsen.json"
    local: "http://0.0.0.0:9007"
  artiklar:
    live: "https://ehalsasverige.se/feed/artiklar/pubmed.json"
    local: "http://0.0.0.0:9004"
  live: "https://ehalsa-sverige-microserver.vercel.app"
  local: "http://0.0.0.0:3000"

#Date
date_format: "%-d/%-m %Y"

#Colours!
color:
  primary: "5472C5"
  dark: "1E2845"
  light: "96A5CE"
  medium: "3F5591"
  highlight: "C4A554"
  shade:
    opacity: "0.3"
    primary: "84, 114, 197"
    dark: "30, 40, 69"
#https://color.adobe.com/sv/create/color-wheel
#Monokrom
#Komplementär

#Artiklar per sida
paginate: 5
paginate_path: "/artiklar/:num/"

# Build settings
#theme: no-style-please
plugins:
  - jekyll-feed
  - jekyll-paginate
theme: minima

serviceworker:
  version: "v1:1:1"
  files: "'/favicon.svg'"
  talk: false

defaults:
  - scope:
      path: "assets/images/post-head"
    values:
      image: true