title: eHälsa Sverige
email: kontakt@example.com
description: "eHälsa Sverige är ett privat initiativ med visionen att vara en samlingsplats för alla som påverkas av eHälsa: patienter, vårdpersonal, beslutsfattare, leverantörer och alla som är nyfikna på att lära sig om eller börja arbeta inom området."
descriptionHTML: "<b>eHälsa Sverige</b> är ett privat initiativ med visionen att vara en samlingsplats för alla som påverkas av eHälsa: patienter, vårdpersonal, beslutsfattare, leverantörer och alla som är nyfikna på att lära sig om eller börja arbeta inom området."
lang: sv
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ehalsasverige.se" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ehälsa-sverige
#github_username:  jekyll

#Colours!
color:
  primary: "5472C5"
  dark: "1E2845"
  light: "96A5CE"
  medium: "3F5591"
  highlight: "C4A554"
  shade:
    opacity: "0.3"
    primary: "84, 114, 197"
    dark: "30, 40, 69"
#https://color.adobe.com/sv/create/color-wheel
#Monokrom
#Komplementär

#Artiklar per sida
paginate: 5
paginate_path: "/artiklar/page:num/"

# Build settings
#theme: no-style-please
plugins:
  - jekyll-feed
  - jekyll-paginate
theme: minima